try adding own whitelist steps

diff --git a/.github/workflows/test-runner-on-perf.yml b/.github/workflows/test-runner-on-perf.yml
--- a/.github/workflows/test-runner-on-perf.yml
+++ b/.github/workflows/test-runner-on-perf.yml
@@ -62,11 +62,26 @@ jobs:
       #      fi
       #    done
       - name: "Whitelist Runner IP"
-        uses: broadinstitute/datarepo-actions@0.22.0
-        with:
-          actions_subcommand: 'gcp_whitelist'
-          role_id: ${{ secrets.ROLE_ID }}
-          secret_id: ${{ secrets.SECRET_ID }}
+        run: |
+          CUR_IPS=$(gcloud container clusters describe ${K8_CLUSTER} --format json | \
+            jq -r '[.masterAuthorizedNetworksConfig.cidrBlocks[] | .cidrBlock]')
+            RUNNER_IP=$(curl 'https://api.ipify.org/?format=text' | xargs printf '[ "%s/32" ]')
+            NEW_IPS=$(printf '%s\n' $CUR_IPS $RUNNER_IP | jq -s -r 'add | unique | join(",")')
+          for i in {1..5}; do
+            if gcloud container clusters update ${K8_CLUSTER} \
+              --enable-master-authorized-networks \
+              --master-authorized-networks ${NEW_IPS}; then
+              echo "Successful whitelist"
+              break
+            else
+              echo "Failed to whitelist - Retrying"
+              sleep 15
+              if [ i == 5 ]; then
+                echo "Failed to whitelist - Terminating"
+                exit 1
+              fi
+            fi
+        done
       - name: "Import Vault dev secrets"
         uses: hashicorp/vault-action@c8b383ee
         with:
@@ -110,9 +125,17 @@ jobs:
           cd ${GITHUB_WORKSPACE}/${workingDir}
       - name: "Clean whitelisted Runner IP"
         if: always()
-        uses: broadinstitute/datarepo-actions@0.22.0
-        with:
-          actions_subcommand: 'gcp_whitelist_clean'
+        run: |
+          # export the original IP list so it can be restored during cleanup
+          CUR_IPS=$(gcloud container clusters describe ${K8_CLUSTER} --format json | \
+            jq -r '[ .masterAuthorizedNetworksConfig.cidrBlocks[] | .cidrBlock ]')
+          RUNNER_IP=$(curl 'https://api.ipify.org/?format=text' | xargs printf '[ "%s/32" ]')
+          RUNNER_IP=$(echo ${RUNNER_IP}| jq -r '.[0]')
+          RESTORE_IPS=$(printf '%s\n' $CUR_IPS | jq -r --arg RUNNER_IP "$RUNNER_IP" '. - [ $RUNNER_IP ] | unique | join(",")')
+          # restore the original list of authorized IPs if they exist
+          gcloud container clusters update ${K8_CLUSTER} \
+            --enable-master-authorized-networks \
+            --master-authorized-networks ${RESTORE_IPS}
       # - name: "Notify Slack"
         #if: always()
         #uses: broadinstitute/action-slack@v2
