hacky

diff --git a/.github/workflows/test-runner-on-perf.yml b/.github/workflows/test-runner-on-perf.yml
--- a/.github/workflows/test-runner-on-perf.yml
+++ b/.github/workflows/test-runner-on-perf.yml
@@ -69,16 +69,9 @@ jobs:
           if [[ -n "${K8_CLUSTER}" ]]; then
             gcloud container clusters get-credentials ${K8_CLUSTER} --zone ${GOOGLE_ZONE}
           fi
-      - name: "Whitelist Runner IP"
-        uses: broadinstitute/datarepo-actions/actions/main@0.39.0
-        env:
-          GOOGLE_SA_CERT: 'jade-dev-account.pem'
-        with:
-          actions_subcommand: 'gcp_whitelist'
-          role_id: ${{ secrets.ROLE_ID }}
-          secret_id: ${{ secrets.SECRET_ID }}
-          google_project: broad-jade-perf
-      - name: '[Update API version on Perf] Checkout datarepo-helm-definitions repo'
+      - name: Add Runner IP to allowlist
+        uses: broadinstitute/datarepo-actions/actions/add-runner-ip@0.49.0
+      - name: 'Checkout datarepo-helm-definitions repo'
         if: ${{ steps.read_property.outputs.LATEST_VERSION != steps.read_property.outputs.CURRENT_SEMVER }}
         uses: actions/checkout@v2
         with:
@@ -98,24 +91,19 @@ jobs:
           GITHUB_REPO: datarepo-helm-definitions
           SWITCH_DIRECTORIES: "true"
           MERGE_BRANCH: master
-      - name: "[Update API version on Perf] Install Helmfile"
-        if: ${{ steps.read_property.outputs.LATEST_VERSION != steps.read_property.outputs.CURRENT_SEMVER }}
+      - name: '[Clean up Perf Database] Set drop all to true'
+        uses: docker://mikefarah/yq:3.3.4
+        with:
+          args: yq w -i datarepo-helm-definitions/perf/datarepo/datarepo-api.yaml env.DB_MIGRATE_DROPALLONSTART true
+      - name: "Install Helmfile"
         uses: broadinstitute/setup-helmfile@v0.6.0 #Forked from mamezou-tech/setup-helmfile
-      - name: "[Update API version on Perf] Use helmfile reapply helm for api pod to update version"
-        if: ${{ steps.read_property.outputs.LATEST_VERSION != steps.read_property.outputs.CURRENT_SEMVER }}
+      - name: "Use helmfile reapply helm for api pod to update version"
         run: |
           helmfile --version
           cd ${GITHUB_WORKSPACE}/${workingDir}/datarepo-helm-definitions/perf
           echo "Apply helm updates, including updated data-repo version"
           helmfile apply
           cd ${GITHUB_WORKSPACE}/${workingDir}
-      - name: "Cycle pods to clear lingering artifacts if not doing version bump"
-        if: ${{ steps.read_property.outputs.LATEST_VERSION == steps.read_property.outputs.CURRENT_SEMVER }}
-        run: |
-          echo "Cycle API pods to trigger migrations to run and clear out database"
-          kubectl delete pods -n perf -l app.kubernetes.io/name=datarepo-api
-          echo "Sleep 45 seconds to give the pods a chance to start cycling before checking if up and on correct version"
-          sleep 45
       - name: "Wait for Perf Cluster to come back up with correct version"
         run: |
           PERF_VERSION=$(curl -s -X GET "https://jade-perf.datarepo-perf.broadinstitute.org/configuration" -H "accept: application/json" | jq -R '. | try fromjson catch {"semVer":"failedToContact"}' | jq -r '.semVer|rtrimstr("-SNAPSHOT")')
@@ -131,34 +119,55 @@ jobs:
             ((RETRY_COUNT=RETRY_COUNT+1))
           done;
           echo "Perf successfully running on new version: $PERF_VERSION"
-      - name: "Build and run Test Runner"
-        run: |
-          cd ${GITHUB_WORKSPACE}/${workingDir}
-          echo "Building Data Repo client library"
-          export TEST_RUNNER_SERVER_SPECIFICATION_FILE="perf.json"
-          ENABLE_SUBPROJECT_TASKS=1 ./gradlew :datarepo-client:clean :datarepo-client:assemble
-          cd ${GITHUB_WORKSPACE}/${workingDir}/datarepo-clienttests
-          export ORG_GRADLE_PROJECT_datarepoclientjar=$(find .. -type f -name "datarepo-client*.jar")
-          echo "ORG_GRADLE_PROJECT_datarepoclientjar = ${ORG_GRADLE_PROJECT_datarepoclientjar}"
-
-          echo "Running test suite"
-          ./gradlew lockAndRunTest --args="suites/NightlyPerfWorkflow.json tmp/TestRunnerResults"
-
-          echo "Collecting measurements"
-          ./gradlew collectMeasurements --args="NightlyPerfWorkflow.json tmp/TestRunnerResults"
-
-          echo "Uploading results"
-          ./gradlew uploadResults --args="BroadJadeDev.json tmp/TestRunnerResults"
-
-          cd ${GITHUB_WORKSPACE}/${workingDir}
-      - name: "Clean whitelisted Runner IP"
-        if: always()
-        uses: broadinstitute/datarepo-actions/actions/main@0.39.0
-        env:
-          GOOGLE_SA_CERT: 'jade-dev-account.pem'
+      - name: '[Clean up Perf Database] Revert drop all to true'
+        uses: docker://mikefarah/yq:3.3.4
         with:
-          actions_subcommand: 'gcp_whitelist_clean'
-          google_project: broad-jade-perf
+          args: yq w -i datarepo-helm-definitions/perf/datarepo/datarepo-api.yaml env.DB_MIGRATE_DROPALLONSTART false
+      - name: "[Clean up Perf Database] Apply revert of drop all to true"
+        run: |
+          helmfile --version
+          cd ${GITHUB_WORKSPACE}/${workingDir}/datarepo-helm-definitions/perf
+          echo "Apply helm updates, including updated data-repo version"
+          helmfile apply
+          cd ${GITHUB_WORKSPACE}/${workingDir}
+      - name: "Wait for Perf Cluster to come back up with correct version"
+        run: |
+          PERF_VERSION=$(curl -s -X GET "https://jade-perf.datarepo-perf.broadinstitute.org/configuration" -H "accept: application/json" | jq -R '. | try fromjson catch {"semVer":"failedToContact"}' | jq -r '.semVer|rtrimstr("-SNAPSHOT")')
+          RETRY_COUNT=0
+          until [[ "$PERF_VERSION" == "${{ steps.read_property.outputs.LATEST_VERSION }}" ]]; do
+            if [[ ${RETRY_COUNT} -gt 20 ]]; then
+              echo "Failed to match perf $PERF_VERSION to dev version ${{ steps.read_property.outputs.LATEST_VERSION }}"
+              exit 1
+            fi
+            echo "Retry #${RETRY_COUNT}: Waiting for $PERF_VERSION to equal ${{ steps.read_property.outputs.LATEST_VERSION }}"
+            sleep 15
+            PERF_VERSION=$(curl -s -X GET "https://jade-perf.datarepo-perf.broadinstitute.org/configuration" -H "accept: application/json" | jq -R '. | try fromjson catch {"semVer":"failedToContact"}' | jq -r '.semVer|rtrimstr("-SNAPSHOT")')
+            ((RETRY_COUNT=RETRY_COUNT+1))
+          done;
+          echo "Perf successfully running on new version: $PERF_VERSION"
+      # - name: "Build and run Test Runner"
+      #   run: |
+      #     cd ${GITHUB_WORKSPACE}/${workingDir}
+      #     echo "Building Data Repo client library"
+      #     export TEST_RUNNER_SERVER_SPECIFICATION_FILE="perf.json"
+      #     ENABLE_SUBPROJECT_TASKS=1 ./gradlew :datarepo-client:clean :datarepo-client:assemble
+      #     cd ${GITHUB_WORKSPACE}/${workingDir}/datarepo-clienttests
+      #     export ORG_GRADLE_PROJECT_datarepoclientjar=$(find .. -type f -name "datarepo-client*.jar")
+      #     echo "ORG_GRADLE_PROJECT_datarepoclientjar = ${ORG_GRADLE_PROJECT_datarepoclientjar}"
+
+      #     echo "Running test suite"
+      #     ./gradlew lockAndRunTest --args="suites/NightlyPerfWorkflow.json tmp/TestRunnerResults"
+
+      #     echo "Collecting measurements"
+      #     ./gradlew collectMeasurements --args="NightlyPerfWorkflow.json tmp/TestRunnerResults"
+
+      #     echo "Uploading results"
+      #     ./gradlew uploadResults --args="BroadJadeDev.json tmp/TestRunnerResults"
+
+      #     cd ${GITHUB_WORKSPACE}/${workingDir}
+      - name: Remove Runner IP from allowlist
+        if: always()
+        uses: broadinstitute/datarepo-actions/actions/rm-runner-ip@0.49.0
       - name: "Notify Jade Slack"
         if: always()
         uses: broadinstitute/action-slack@v3.8.0
