fix formatting

diff --git a/.github/workflows/test-runner-on-perf.yml b/.github/workflows/test-runner-on-perf.yml
--- a/.github/workflows/test-runner-on-perf.yml
+++ b/.github/workflows/test-runner-on-perf.yml
@@ -63,25 +63,30 @@ jobs:
       #    done
       - name: "Whitelist Runner IP"
         run: |
-          CUR_IPS=$(gcloud container clusters describe ${K8_CLUSTER} --format json | \
-            jq -r '[.masterAuthorizedNetworksConfig.cidrBlocks[] | .cidrBlock]')
-            RUNNER_IP=$(curl 'https://api.ipify.org/?format=text' | xargs printf '[ "%s/32" ]')
-            NEW_IPS=$(printf '%s\n' $CUR_IPS $RUNNER_IP | jq -s -r 'add | unique | join(",")')
-          for i in {1..5}; do
-            if gcloud container clusters update ${K8_CLUSTER} \
-              --enable-master-authorized-networks \
-              --master-authorized-networks ${NEW_IPS}; then
-              echo "Successful whitelist"
-              break
-            else
-              echo "Failed to whitelist - Retrying"
-              sleep 15
-              if [ i == 5 ]; then
-                echo "Failed to whitelist - Terminating"
-                exit 1
+          if [[ "${K8_CLUSTER}" != "" ]]; then
+            CUR_IPS=$(gcloud container clusters describe ${K8_CLUSTER} --format json | \
+              jq -r '[.masterAuthorizedNetworksConfig.cidrBlocks[] | .cidrBlock]')
+              RUNNER_IP=$(curl 'https://api.ipify.org/?format=text' | xargs printf '[ "%s/32" ]')
+              NEW_IPS=$(printf '%s\n' $CUR_IPS $RUNNER_IP | jq -s -r 'add | unique | join(",")')
+            for i in {1..5}; do
+              if gcloud container clusters update ${K8_CLUSTER} \
+                --enable-master-authorized-networks \
+                --master-authorized-networks ${NEW_IPS}; then
+                echo "Successful whitelist"
+                break
+              else
+                echo "Failed to whitelist - Retrying"
+                sleep 15
+                if [ i == 5 ]; then
+                  echo "Failed to whitelist - Terminating"
+                  exit 1
+                fi
               fi
-            fi
-        done
+            done
+          else
+            echo "Required var not defined for function whitelist"
+            exit 1
+          fi
       - name: "Import Vault dev secrets"
         uses: hashicorp/vault-action@c8b383ee
         with:
